name: mlops-2026-1
services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped

  mlops-container:
    container_name: mlops-container
    build:
      context: .
      dockerfile: app/app.Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      MONGO_URI: mongodb://mongo:27017
    restart: unless-stopped
    depends_on:
      - mongo
